#!/usr/bin/env bash
# based on https://gist.github.com/sindresorhus/7996717

changed_files="$(git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && echo " * changes detected in $1" && echo " * running $2" && eval "$2"
}

check_run .recipients.asc "gpg --import .recipients.asc"
